import assert from 'node:assert/strict'
import { mkdir, writeFile, readFile, unlink, utimes, readdir } from 'node:fs/promises'
import path from 'node:path'
import http from 'node:http'
import { closeDustDesk, launchDustDesk } from './electron-harness.mjs'

let app = await launchDustDesk()
const server = http.createServer((request, response) => { response.writeHead(request.url === '/private' ? 403 : 200); response.end('test') })
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
const url = `http://127.0.0.1:${server.address().port}`
const errors = []
app.window.on('pageerror', error => errors.push(error.message))
const load = () => app.window.evaluate(() => window.dustdesk.loadWorkspace())
const action = value => app.window.evaluate(value => window.dustdesk.productivity(value), value)
const update = fn => app.window.evaluate(async source => { const state = await window.dustdesk.loadWorkspace(); const next = structuredClone(state); new Function('state', source)(next); await window.dustdesk.saveWorkspace(next, state) }, fn)
async function waitForState(predicate) {
  for (let attempt = 0; attempt < 100; attempt++) {
    const current = await load()
    if (predicate(current)) return current
    await new Promise(resolve => setTimeout(resolve, 50))
  }
  throw new Error('Timed out waiting for persisted workspace state')
}
const navigate = text => app.window.locator('.sidebar').getByRole('button', { name: text, exact: true }).click()
try {
  await update('state.Settings.ClipboardMonitoringEnabled = false')
  for (const kind of ['task', 'note']) assert.equal((await action({ type: 'capture', kind, title: `Recycle ${kind}`, text: 'retained text' })).ok, true)
  const original = await load()
  await update("state.Todos = state.Todos.filter(item => item.Title !== 'Recycle task'); state.Notes = state.Notes.filter(item => item.Title !== 'Recycle note')")
  assert.equal((await load()).RecycleBin.length, 2)
  await navigate('回收站')
  await app.window.getByRole('button', { name: '恢复', exact: true }).first().click()
  await app.window.waitForFunction(() => document.querySelectorAll('.feature-row').length === 1)
  await app.window.getByRole('button', { name: '恢复', exact: true }).first().click()
  await waitForState(state => state.RecycleBin.length === 0)
  assert.equal((await load()).RecycleBin.length, 0)
  assert.equal((await load()).Notes.find(item => item.Title === 'Recycle note').Text, 'retained text')
  console.log('Recycle bin delete, restore and full payload passed')

  await navigate('设置')
  await app.window.getByRole('button', { name: '打开快速记录', exact: true }).click()
  const capture = app.electronApp.windows().find(page => page.url().includes('capture=')) ?? await app.electronApp.waitForEvent('window')
  await capture.getByLabel('记录标题').fill('Captured from shortcut window')
  await capture.getByLabel('记录正文').fill('capture details')
  await capture.getByLabel('记录正文').press('Control+Enter')
  await waitForState(state => state.Todos.some(item => item.Title === 'Captured from shortcut window'))
  await app.window.evaluate(() => window.dustdesk.showQuickCapture())
  assert.equal(await capture.getByLabel('记录标题').inputValue(), '')
  await capture.getByLabel('记录标题').fill('unsaved draft')
  await capture.getByLabel('记录标题').press('Escape')
  await app.window.evaluate(() => window.dustdesk.showQuickCapture())
  assert.equal(await capture.getByLabel('记录标题').inputValue(), 'unsaved draft')
  await app.window.evaluate(() => window.dustdesk.hideQuickCapture())
  assert.equal((await app.window.evaluate(() => window.dustdesk.setHotkeys({ quickCapture: 'Ctrl+Shift+K' }))).ok, false)
  console.log('Quick capture keyboard save, hide, draft and shortcut conflict passed')

  const widgetPromise = app.electronApp.waitForEvent('window')
  await app.window.evaluate(() => window.dustdesk.toggleWidgets('todo'))
  const widget = await widgetPromise
  await widget.getByLabel('桌面新增任务').fill('Desktop direct task')
  await widget.getByLabel('桌面新增任务').press('Enter')
  await widget.getByRole('checkbox', { name: '完成 Desktop direct task', exact: true }).click()
  await waitForState(state => state.Todos.find(item => item.Title === 'Desktop direct task')?.IsCompleted)
  const notePromise = app.electronApp.waitForEvent('window')
  await app.window.evaluate(() => window.dustdesk.toggleWidgets('notes'))
  const notes = await notePromise
  await notes.getByLabel('便签正文').fill('Changed on desktop')
  await notes.getByLabel('便签正文').press('Control+Enter')
  await waitForState(state => state.Notes.some(item => item.Text === 'Changed on desktop'))
  await notes.getByLabel('便签标题').fill('  Desktop title  ')
  await notes.getByRole('button', { name: '保存', exact: true }).click()
  await waitForState(state => state.Notes.some(item => item.Title === 'Desktop title'))
  await notes.getByLabel('便签正文').fill('second save after title trim')
  await notes.getByLabel('便签正文').press('Control+Enter')
  await waitForState(state => state.Notes.some(item => item.Text === 'second save after title trim'))
  await notes.getByLabel('便签正文').fill('local draft')
  await update("state.Notes[0].Text = 'edited elsewhere'")
  await notes.getByRole('button', { name: '保存', exact: true }).click()
  await notes.getByRole('alert').waitFor()
  assert.equal(await notes.getByLabel('便签正文').inputValue(), 'local draft')
  // A hidden conflicting draft must survive the later restart without a workaround.
  await app.window.evaluate(() => window.dustdesk.hideWidget('notes'))
  console.log('Desktop task add/complete, note save and conflict protection passed')

  const data = path.join(app.tempRoot, 'data')
  const desktop = path.join(app.tempRoot, 'desktop')
  await mkdir(desktop, { recursive: true })
  await writeFile(path.join(desktop, 'invoice.PDF'), 'invoice')
  await writeFile(path.join(desktop, 'unmatched.txt'), 'unmatched')
  const category = (await load()).DesktopCategories[1]
  await navigate('桌面收纳')
  await app.window.getByLabel('匹配方式').selectOption('name')
  await app.window.getByLabel('规则内容').fill('invoice')
  await app.window.getByLabel('规则目标分类').selectOption(category.Id)
  await app.window.getByRole('button', { name: '新增规则', exact: true }).click()
  await waitForState(state => state.OrganizerRules.length === 1)
  const plan = await app.window.evaluate(() => window.dustdesk.planSmartOrganize())
  assert.equal(plan.find(item => item.SourcePath.endsWith('invoice.PDF')).CategoryId, category.Id)
  await writeFile(path.join(desktop, 'after-preview.txt'), 'must remain')
  const execution = await app.window.evaluate(plan => window.dustdesk.executeSmartOrganize(plan), plan)
  assert.equal(execution.ok, true); assert.equal(execution.moved, 2)
  assert.equal(await readFile(path.join(desktop, 'after-preview.txt'), 'utf8'), 'must remain')
  assert.equal((await app.window.evaluate(() => window.dustdesk.undoOrganizerMove())).ok, true)
  assert.equal((await app.window.evaluate(() => window.dustdesk.undoOrganizerMove())).ok, true)
  assert.equal(await readFile(path.join(desktop, 'invoice.PDF'), 'utf8'), 'invoice')
  assert.equal((await app.window.evaluate(() => window.dustdesk.executeSmartOrganize())).ok, false)
  console.log('Organizer custom rules, exact preview and undo passed')

  const missing = path.join(app.tempRoot, 'missing.exe')
  await app.window.evaluate(async ({ missing, url }) => {
    const state = await window.dustdesk.loadWorkspace(); const next = structuredClone(state)
    next.Launchers.push({ Id: 'missing-launcher', Name: 'Missing launcher', Path: missing })
    next.LinkGroups[0].Links.push({ Id: 'http-test', Name: 'HTTP only', Url: url, Note: '', CreatedAt: '', UpdatedAt: '' }, { Id: 'private-test', Name: 'Auth protected', Url: `${url}/private`, Note: '', CreatedAt: '', UpdatedAt: '' })
    await window.dustdesk.saveWorkspace(next, state)
  }, { missing, url })
  const resources = await app.window.evaluate(() => window.dustdesk.checkResources())
  assert.equal(resources.find(item => item.id === 'missing-launcher').status, 'missing')
  assert.equal(resources.find(item => item.id === 'http-test').status, 'ok')
  assert.equal(resources.find(item => item.id === 'private-test').status, 'warning')
  assert.equal((await action({ type: 'resource-relink', resource: resources.find(item => item.id === 'missing-launcher'), replacement: path.join(desktop, 'invoice.PDF') })).ok, true)
  assert.equal((await load()).LinkGroups[0].Links.length, 2)
  console.log('Resource missing paths, HTTP without auto-upgrade, warnings and relink passed')

  await navigate('专注计时')
  await app.window.getByLabel('关联任务').selectOption(original.Todos[0].Id)
  await app.window.getByLabel('专注分钟').fill('1')
  await app.window.getByRole('button', { name: '开始专注', exact: true }).click()
  await app.window.getByRole('button', { name: '暂停', exact: true }).waitFor()
  await new Promise(resolve => setTimeout(resolve, 1200))
  await app.window.getByRole('button', { name: '暂停', exact: true }).click()
  await waitForState(state => state.ActiveFocus?.RunningSince === null)
  assert.equal((await load()).ActiveFocus.RunningSince, null)
  await app.window.getByRole('button', { name: '结束并记录', exact: true }).click()
  await waitForState(state => state.FocusSessions.length === 1)
  assert.ok((await load()).FocusSessions[0].Seconds >= 1)
  console.log('Focus timer UI, pause and actual task-linked statistics passed')

  assert.equal((await action({ type: 'focus-start', taskId: '', projectId: '', minutes: 25 })).ok, true)
  await waitForState(state => state.ActiveFocus && Date.parse(state.ActiveFocus.CheckpointAt) > Date.parse(state.ActiveFocus.RunningSince))
  const imageRoot = path.join(data, 'NoteBackgrounds'); await mkdir(imageRoot, { recursive: true })
  const image = path.join(imageRoot, 'test.png'); const bytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')
  await writeFile(image, bytes)
  await app.window.evaluate(async image => { const state = await window.dustdesk.loadWorkspace(); const next = structuredClone(state); next.Notes[0].BackgroundImagePath = image; next.Notes[0].BackgroundImageFileName = 'test.png'; await window.dustdesk.saveWorkspace(next, state) }, image)
  const backup = await app.window.evaluate(() => window.dustdesk.createBackup()); assert.equal(backup.ok, true)
  const backupSnapshot = JSON.parse(await readFile(backup.path, 'utf8'))
  const checkpointSeconds = (Date.parse(backupSnapshot.ActiveFocus.CheckpointAt) - Date.parse(backupSnapshot.ActiveFocus.RunningSince)) / 1000 + backupSnapshot.ActiveFocus.ElapsedSeconds
  const preview = await app.window.evaluate(target => window.dustdesk.previewBackup(target), backup.path)
  assert.equal(preview.tasks, (await load()).Todos.length)
  await unlink(image)
  await action({ type: 'capture', kind: 'task', title: 'Before restore safety', text: '' })
  assert.equal((await app.window.evaluate(({ path, fingerprint }) => window.dustdesk.restoreBackup(path, fingerprint), { path: backup.path, fingerprint: 'outdated' })).ok, false)
  assert.equal((await app.window.evaluate(preview => window.dustdesk.restoreBackup(preview.path, preview.fingerprint), preview)).ok, true)
  const restored = await load()
  assert.equal(restored.Todos.some(item => item.Title === 'Before restore safety'), false)
  assert.equal(restored.ActiveFocus.RunningSince, null)
  assert.equal(restored.ActiveFocus.ElapsedSeconds, checkpointSeconds)
  assert.equal((await action({ type: 'focus-cancel' })).ok, true)
  assert.deepEqual(await readFile(restored.Notes[0].BackgroundImagePath), bytes)
  const points = await app.window.evaluate(() => window.dustdesk.listBackups())
  const safety = points.find(item => item.name.startsWith('before-restore-')); assert.ok(safety)
  assert.equal((await app.window.evaluate(target => window.dustdesk.previewBackup(target), safety.path)).warnings.length, 1)
  assert.ok(JSON.parse(await readFile(safety.path, 'utf8')).Todos.some(item => item.Title === 'Before restore safety'))
  assert.ok(points.some(item => item.name.startsWith('auto-')))
  console.log('Backup preview, fingerprint, embedded images and pre-restore protection passed')

  const artifacts = path.resolve('artifacts/productivity'); await mkdir(artifacts, { recursive: true })
  await navigate('专注计时'); await app.window.screenshot({ path: path.join(artifacts, 'focus.png') })
  await navigate('设置'); await app.window.getByRole('button', { name: '深色', exact: true }).click()
  await app.window.getByRole('button', { name: '刷新备份', exact: true }).click()
  await app.window.getByRole('button', { name: '预览恢复', exact: true }).first().click()
  await app.window.getByRole('region', { name: '恢复预览' }).waitFor()
  await app.window.screenshot({ path: path.join(artifacts, 'backup-dark.png') })
  await widget.screenshot({ path: path.join(artifacts, 'widget-task.png') })
  assert.deepEqual(errors, [])

  const root = app.tempRoot
  const autoOld = path.join(data, 'Backups', 'auto-expired.json'); const manualOld = path.join(data, 'Backups', 'manual-old.json')
  await writeFile(autoOld, JSON.stringify(restored)); await writeFile(manualOld, JSON.stringify(restored))
  const oldDate = new Date(Date.now() - 40 * 86400000); await utimes(autoOld, oldDate, oldDate); await utimes(manualOld, oldDate, oldDate)
  await action({ type: 'focus-start', taskId: '', projectId: '', minutes: 25 })
  const beforeCrash = (await load()).ActiveFocus
  await closeDustDesk({ ...app, preserveTempRoot: true })
  app = await launchDustDesk({ tempRoot: root })
  await waitForState(state => state.ActiveFocus?.RunningSince === null)
  assert.equal((await load()).ActiveFocus.Id, beforeCrash.Id)
  await waitForState(() => true)
  for (let attempt = 0; attempt < 100 && (await readdir(path.join(data, 'Backups'))).includes('auto-expired.json'); attempt++) await new Promise(resolve => setTimeout(resolve, 50))
  assert.equal((await readdir(path.join(data, 'Backups'))).includes('auto-expired.json'), false)
  assert.ok((await readdir(path.join(data, 'Backups'))).includes('manual-old.json'))
  const recoveredNotesPromise = app.electronApp.waitForEvent('window')
  await app.window.evaluate(() => window.dustdesk.toggleWidgets('notes'))
  const recoveredNotes = await recoveredNotesPromise
  assert.equal(await recoveredNotes.getByLabel('便签正文').inputValue(), 'local draft')
  console.log('Restart focus recovery and automatic-only backup retention passed')
  console.log('All seven productivity feature flows passed')
} finally {
  await new Promise(resolve => server.close(resolve))
  await closeDustDesk(app)
}
