import { useEffect, useState } from 'react'
import { ChevronDown, ChevronUp, FolderOpen, EyeOff, Lock, Magnet, Pin, TimerReset } from 'lucide-react'
import { toast } from 'sonner'
import type { WidgetPlacement, WorkspaceState } from '../../../shared/types'
import { argbCss } from '../utils/colors'
import { WidgetResizeGrip } from './WidgetResizeGrip'
import { useWidgetDrag } from './useWidgetDrag'

export function OrganizerGroupWidget({ state, groupKey }: { state: WorkspaceState; groupKey: string }) {
  const ids = new Set(groupKey.split(',').filter(Boolean)); const categories = state.DesktopCategories.filter(category => ids.has(category.Id)); const key = `organizer-group:${groupKey}`; const placement = (state.Settings.WidgetPlacements?.[key] ?? {}) as WidgetPlacement; const [collapsed, setCollapsed] = useState(Boolean(placement.IsCollapsed)); const drag = useWidgetDrag(key)
  useEffect(() => { setCollapsed(Boolean(placement.IsCollapsed)); if (!placement.AutoCollapseEnabled) return; const timer = window.setTimeout(() => { setCollapsed(true); void window.dustdesk.setWidgetOptions(key, { collapsed: true }) }, 10_000); return () => window.clearTimeout(timer) }, [placement.AutoCollapseEnabled, placement.IsCollapsed, key])
  const setOption = async (option: Parameters<typeof window.dustdesk.setWidgetOptions>[1]) => { const result = await window.dustdesk.setWidgetOptions(key, option); if (!result.ok) toast.error(result.error ?? '小组件设置失败') }
  return <div className={`widget-shell ${collapsed ? 'widget-collapsed' : ''}`} style={{ background: argbCss(state.Settings.WidgetBackgroundColorArgb ?? -1, placement.TransparentBackground ? 72 / 255 : 245 / 255) }}><div className="widget-head" {...drag}><div className="widget-title-drag" data-widget-drag-handle><h2>收纳组合</h2></div><div className="widget-controls"><button className={`mini-button ${placement.Locked ? 'selected' : ''}`} title="锁定大小" onClick={() => void setOption({ locked: !placement.Locked })}><Lock size={13} /></button><button className={`mini-button ${placement.TopMost ? 'selected' : ''}`} title="置顶" onClick={() => void setOption({ topMost: !placement.TopMost })}><Pin size={13} /></button><button className={`mini-button ${placement.TransparentBackground ? 'selected' : ''}`} title="透明背景" onClick={() => void setOption({ transparentBackground: !placement.TransparentBackground })}><EyeOff size={13} /></button><button className={`mini-button ${placement.AutoCollapseEnabled ? 'selected' : ''}`} title="10 秒后自动折叠" onClick={() => void setOption({ autoCollapse: !placement.AutoCollapseEnabled })}><TimerReset size={13} /></button><button className={`mini-button ${placement.SnapToEdges ? 'selected' : ''}`} title="吸附屏幕边缘" onClick={() => void setOption({ snapToEdges: !placement.SnapToEdges })}><Magnet size={13} /></button><button className="mini-button widget-collapse-toggle" title={collapsed ? '展开' : '折叠'} aria-expanded={!collapsed} onClick={() => { const next = !collapsed; setCollapsed(next); void setOption({ collapsed: next }) }}>{collapsed ? <ChevronUp size={13} /> : <ChevronDown size={13} />}</button></div></div>{!collapsed && <div className="widget-content"><div className="widget-todos">{categories.map(category => <div className="widget-todo" key={category.Id}><span>{category.Name}</span><small>{category.ItemPaths.length} 项</small></div>)}{!categories.length && <div className="widget-empty"><FolderOpen size={17} />组合分类已移除</div>}</div></div>}{!collapsed && <WidgetResizeGrip widgetKey={key} locked={placement.Locked} />}</div>
}
