import { productivityDefaults, productivitySettings } from '../../../shared/productivity'
import type { AppSettings, WorkspaceState } from '../../../shared/types'
import { now, uid } from '../utils/ids'

export function starterState(): WorkspaceState {
  const time = now()
  const settings = { ...productivitySettings, Theme: 'light' as const, MainWindowDisplayName: 'DustDesk', StartHiddenToTray: false, StartWithWindows: false, MainWindowHotKey: 'Ctrl+Shift+K', DesktopWidgetsHotKey: 'Ctrl+Shift+D', ScreenshotHotKey: 'Ctrl+Shift+S', PinScreenshotHotKey: 'F3', ScreenshotFormat: 'png', ScreenshotSaveDirectory: '', ScreenshotDelaySeconds: 0, ScreenshotAfterAction: 'edit', ScreenshotAutoCopy: true, ScreenshotAutoAddToClipboardHistory: true, PinnedImageTopmost: true, PinnedImageOpacityPercent: 100, PinnedImageMouseThrough: false, WidgetOpacityPercent: 86, WidgetBackgroundColorArgb: -1, SearchDesktopFiles: true, SearchAppData: true, SearchStartMenuApps: true, SearchProjectPaths: true, SearchCustomPaths: true, SearchCustomRoots: [], ClipboardMonitoringEnabled: true, DesktopHotKeyWidgetKeys: ['organizer'], LauncherWidgetSnapToEdges: false, LauncherWidgetShowNames: true, LauncherWidgetIconSize: 48, OrganizerWidgetShowNames: false, OrganizerWidgetIconSize: 48, MonitorShowDownload: true, MonitorShowUpload: true, MonitorShowMemory: true, MonitorShowCpu: true, MonitorShowDiskIo: true, MonitorShowDiskSpace: true, MonitorShowPing: true, MonitorShowUptime: true, WorkdayStartMinutes: 540, WorkdayEndMinutes: 1080, MonthlySalary: 0, PaydayDay: 10, CountdownFestivalName: '国庆节', CountdownFestivalMonth: 10, CountdownFestivalDay: 1, WidgetPlacements: {}, NoteWidgetPlacements: [], OrganizerGroupWidgetPlacements: [], WidgetLayoutPresets: {} } as AppSettings
  return { ...productivityDefaults(), SchemaVersion: 3, LegacyImportCompleted: false, QuickNote: '', Settings: settings, Todos: [], TagPresets: [], Notes: [{ Id: uid(), Title: '快速便签', Text: '', ColorArgb: -411768, FontColorArgb: -1385444, FontSize: 14, FontBold: false, BackgroundImageFileName: '', ImageOnly: false, CreatedAt: time, UpdatedAt: time }], Projects: [], Launchers: [], LinkGroups: [{ Id: uid(), Name: '常用', Links: [] }], ClipboardHistory: [], DesktopCategories: ['工作', '开发', '工具', '文件'].map(Name => ({ Id: uid(), Name, IsCollapsed: false, ItemPaths: [] })) }
}
